
import io
from datetime import datetime
from decimal import Decimal, InvalidOperation

import streamlit as st
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image

# -----------------------------
# Configuration / Preferences
# -----------------------------
APP_TITLE = "Legal Billing PDF Generator"
CURRENCY = "AED"
AUTO_CALC_CLERAGE = True     # If True, clerage @10% is auto-computed; otherwise user-provided
CLERAGE_RATE = Decimal("0.10")

# -----------------------------
# Helpers
# -----------------------------
def d(x) -> Decimal:
    """Safe Decimal conversion; empty/None -> 0"""
    if x is None:
        return Decimal("0")
    if isinstance(x, (int, float, Decimal)):
        return Decimal(str(x))
    s = str(x).strip()
    if s == "":
        return Decimal("0")
    try:
        return Decimal(s)
    except (InvalidOperation, ValueError):
        return Decimal("0")

def money(val: Decimal) -> str:
    return f"{CURRENCY} {val:,.2f}"

def build_pdf(data: dict, logo_path: str | None = None) -> bytes:
    """
    Create a PDF and return bytes.
    data contains:
      - case fields: date, case_no, petitioner, respondent
      - fee fields as Decimals
      - computed: subtotal, clerage, grand_total
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title="Legal Billing Statement",
        author="Generated by Streamlit",
    )

    elements = []

    # Header
    if logo_path:
        try:
            im = Image(logo_path, width=35 * mm, height=35 * mm)
            elements.append(im)
            elements.append(Spacer(1, 6))
        except Exception:
            # Ignore logo errors
            pass

    title_style = ParagraphStyle(
        name="Title",
        fontName="Helvetica-Bold",
        fontSize=16,
        spaceAfter=8,
    )
    subtitle_style = ParagraphStyle(
        name="Subtitle",
        fontName="Helvetica",
        fontSize=10,
        textColor=colors.grey,
        spaceAfter=8,
    )
    section_style = ParagraphStyle(
        name="Section",
        fontName="Helvetica-Bold",
        fontSize=12,
        spaceBefore=10,
        spaceAfter=6,
    )
    normal_style = ParagraphStyle(
        name="Normal",
        fontName="Helvetica",
        fontSize=10,
        leading=14,
    )

    elements.append(Paragraph("Legal Billing Statement", title_style))
    elements.append(Paragraph(f"Generated on {datetime.now().strftime('%d-%b-%Y %H:%M')}", subtitle_style))

    # Case details as table
    elements.append(Paragraph("Case Details", section_style))
    case_tbl_data = [
        ["Date", data.get("date") or "" , "Case No", data.get("case_no") or ""],
        ["Petitioner", data.get("petitioner") or "", "Respondent", data.get("respondent") or ""],
    ]
    case_tbl = Table(case_tbl_data, colWidths=[30*mm, 60*mm, 30*mm, 60*mm])
    case_tbl.setStyle(TableStyle([
        ("BOX", (0,0), (-1,-1), 0.6, colors.black),
        ("INNERGRID", (0,0), (-1,-1), 0.3, colors.black),
        ("BACKGROUND", (0,0), (-1,0), colors.whitesmoke),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("FONT", (0,0), (-1,-1), "Helvetica", 10),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ]))
    elements.append(case_tbl)
    elements.append(Spacer(1, 8))

    # Fees Table
    elements.append(Paragraph("Fee Components", section_style))

    # Build line items
    line_items = []
    def add_line(label: str, amount: Decimal):
        line_items.append([label, money(amount)])

    add_line("Fees for non-effective hearing", data["fees_non_effective"])
    add_line("Fees for drafting of counter / show cause / replies", data["fees_drafting_counter"])
    add_line("Fees for drafting of M.A. / hearing fees for M.A. & compliance", data["fees_drafting_ma"])
    add_line("Fees for drafting opinion", data["fees_opinion"])
    add_line("Fee for drafting reply to rejoinder / petition", data["fees_reply_rejoinder"])
    # Clerage added later (computed or manual)
    add_line("Cost of certified copy of order / judgment", data["cost_certified_copy"])
    add_line("Cost of type paper and typing", data["cost_type_typing"])
    add_line("Cost type paper & other misc. expenditure", data["cost_misc"])
    add_line("Out-of-pocket expenses", data["out_of_pocket"])
    add_line("Court fee paid on affidavit / appearance memo / petition", data["court_fee"])
    add_line("Conferencing and consultation charges", data["conferencing"])
    conv_label = "Conveyance charges"
    if data.get("conveyance_from"):
        conv_label += f" (From: {data['conveyance_from']})"
    add_line(conv_label, data["conveyance_amount"])

    # Table data with header
    fees_tbl_data = [["Description", "Amount"]] + line_items
    fees_tbl = Table(fees_tbl_data, colWidths=[130*mm, 40*mm])
    fees_tbl.setStyle(TableStyle([
        ("BOX", (0,0), (-1,-1), 0.6, colors.black),
        ("INNERGRID", (0,0), (-1,-1), 0.3, colors.black),
        ("BACKGROUND", (0,0), (-1,0), colors.whitesmoke),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONT", (0,0), (-1,-1), "Helvetica", 10),
        ("ALIGN", (1,1), (1,-1), "RIGHT"),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
    ]))
    elements.append(fees_tbl)
    elements.append(Spacer(1, 6))

    # Totals
    totals_tbl_data = []
    totals_tbl_data.append(["Subtotal (before Clerage)", money(data["subtotal"])])
    totals_tbl_data.append([f"Clerage @ {int(CLERAGE_RATE*100)}%", money(data["clerage"])])
    totals_tbl_data.append(["Grand Total", money(data["grand_total"])])

    totals_tbl = Table(totals_tbl_data, colWidths=[130*mm, 40*mm])
    totals_tbl.setStyle(TableStyle([
        ("BOX", (0,0), (-1,-1), 0.6, colors.black),
        ("INNERGRID", (0,0), (-1,-1), 0.3, colors.black),
        ("FONT", (0,0), (-1,-1), "Helvetica", 10),
        ("ALIGN", (1,0), (1,-1), "RIGHT"),
        ("BACKGROUND", (0,2), (-1,2), colors.lightgrey),
        ("FONTNAME", (0,2), (-1,2), "Helvetica-Bold"),
    ]))
    elements.append(totals_tbl)
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("Notes", section_style))
    elements.append(Paragraph(
        "This is a system-generated statement. Please review the details. "
        "For queries, contact the issuing office.", normal_style
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()

# -----------------------------
# Streamlit UI
# -----------------------------
st.set_page_config(page_title=APP_TITLE, page_icon="📄", layout="centered")
st.title(APP_TITLE)
st.caption("Enter case details and fee components to generate a formatted preview and PDF.")

with st.form("billing_form", clear_on_submit=False):
    st.subheader("1) Case Details")
    col1, col2 = st.columns(2)
    with col1:
        date_str = st.date_input("Date", format="DD/MM/YYYY")
        case_no = st.text_input("Case No")
        petitioner = st.text_input("Petitioner")
    with col2:
        respondent = st.text_input("Respondent")

    st.subheader("2) Fee Components (amounts in AED)")
    f1 = st.number_input("Fees for non-effective hearing", min_value=0.0, step=100.0)
    f2 = st.number_input("Fees for drafting of counter / show cause / replies", min_value=0.0, step=100.0)
    f3 = st.number_input("Fees for drafting of M.A. / hearing fees for M.A. & compliance", min_value=0.0, step=100.0)
    f4 = st.number_input("Fees for drafting opinion", min_value=0.0, step=100.0)
    f5 = st.number_input("Fee for drafting reply to rejoinder / petition", min_value=0.0, step=100.0)

    if AUTO_CALC_CLERAGE:
        st.info("Clerage @10% will be auto-calculated on subtotal.")
        clerage_user = 0.0
    else:
        clerage_user = st.number_input("Clerage Charge @10% (enter amount if not auto-calculated)", min_value=0.0, step=50.0)

    c1 = st.number_input("Cost of certified copy of order / judgment", min_value=0.0, step=50.0)
    c2 = st.number_input("Cost of type paper and typing", min_value=0.0, step=50.0)
    c3 = st.number_input("Cost type paper & other misc. expenditure", min_value=0.0, step=50.0)
    c4 = st.number_input("Out-of-pocket expenses", min_value=0.0, step=50.0)
    c5 = st.number_input("Court fee paid on affidavit / appearance memo / petition", min_value=0.0, step=50.0)
    c6 = st.number_input("Conferencing and consultation charges", min_value=0.0, step=50.0)

    col_cf = st.columns([2, 1])
    with col_cf[0]:
        conveyance_from = st.text_input("Conveyance Charged From (e.g., Office to Court X)")
    with col_cf[1]:
        conveyance_amount = st.number_input("Conveyance Amount", min_value=0.0, step=50.0)

    submitted = st.form_submit_button("Generate Preview & PDF")

if submitted:
    # Prepare numeric values (as Decimal)
    vals = {
        "fees_non_effective": d(f1),
        "fees_drafting_counter": d(f2),
        "fees_drafting_ma": d(f3),
        "fees_opinion": d(f4),
        "fees_reply_rejoinder": d(f5),
        "cost_certified_copy": d(c1),
        "cost_type_typing": d(c2),
        "cost_misc": d(c3),
        "out_of_pocket": d(c4),
        "court_fee": d(c5),
        "conferencing": d(c6),
        "conveyance_amount": d(conveyance_amount),
    }

    # Subtotal: sum of all fees except clerage (computed separately)
    subtotal = sum(vals.values(), Decimal("0"))

    # Clerage handling
    if AUTO_CALC_CLERAGE:
        clerage = (subtotal * CLERAGE_RATE).quantize(Decimal("0.01"))
    else:
        clerage = d(clerage_user)

    grand_total = (subtotal + clerage).quantize(Decimal("0.01"))

    # Build a display table (preview)
    st.success("Preview generated. Review below and download the PDF.")
    st.markdown("### Case Details")
    st.write(
        f"**Date:** {date_str.strftime('%d/%m/%Y') if date_str else ''}  \n"
        f"**Case No:** {case_no or ''}  \n"
        f"**Petitioner:** {petitioner or ''}  \n"
        f"**Respondent:** {respondent or ''}"
    )

    st.markdown("### Fee Components")
    preview_rows = [
        ("Fees for non-effective hearing", vals["fees_non_effective"]),
        ("Fees for drafting of counter / show cause / replies", vals["fees_drafting_counter"]),
        ("Fees for drafting of M.A. / hearing fees for M.A. & compliance", vals["fees_drafting_ma"]),
        ("Fees for drafting opinion", vals["fees_opinion"]),
        ("Fee for drafting reply to rejoinder / petition", vals["fees_reply_rejoinder"]),
        ("Cost of certified copy of order / judgment", vals["cost_certified_copy"]),
        ("Cost of type paper and typing", vals["cost_type_typing"]),
        ("Cost type paper & other misc. expenditure", vals["cost_misc"]),
        ("Out-of-pocket expenses", vals["out_of_pocket"]),
        ("Court fee paid on affidavit / appearance memo / petition", vals["court_fee"]),
        ("Conferencing and consultation charges", vals["conferencing"]),
        (f"Conveyance charges (From: {conveyance_from})" if conveyance_from else "Conveyance charges", vals["conveyance_amount"]),
    ]

    for label, amount in preview_rows:
        st.write(f"- **{label}:** {money(amount)}")

    st.markdown("### Totals")
    st.write(f"**Subtotal (before Clerage):** {money(subtotal)}")
    st.write(f"**Clerage @ {int(CLERAGE_RATE*100)}%:** {money(clerage)}")
    st.write(f"**Grand Total:** {money(grand_total)}")

    # Assemble data for PDF
    pdf_data = {
        "date": date_str.strftime("%d/%m/%Y") if date_str else "",
        "case_no": case_no,
        "petitioner": petitioner,
        "respondent": respondent,
        **vals,
        "conveyance_from": conveyance_from,
        "subtotal": subtotal,
        "clerage": clerage,
        "grand_total": grand_total,
    }

    # Build PDF bytes
    pdf_bytes = build_pdf(pdf_data, logo_path="assets/logo.png")

    # Download button
    filename = f"Legal_Billing_{case_no or 'statement'}_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
    st.download_button(
        label="⬇️ Download PDF",
        data=pdf_bytes,
        file_name=filename,
        mime="application/pdf",
    )

    st.caption("If the logo is missing, add `assets/logo.png` or remove the path in code.")

# Footer
st.markdown("---")
st.caption("Built with Streamlit & ReportLab. You can customize styling, rates, and fields as needed.")
